# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f1de38fd156b9dd9d7d0d2bcef710d614d35435f6aab906d30cda6c5c51d9425a8252201cf6e26c3d6030a4f7ec41582b85b5e9b6691df5b56496bc92e9a405

test:
  secret_key_base: 6d3d92d3a907f1156d3cceb7bcc4d1ea8535a8376147a16e22b822f774502f9484e3db44905def2fba0c7389eee4252e2febf26d0f192f018604db25c9052549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
